name: Deploy site to S3
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  update-site:
    name: Update public site
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e9d3185f7a72ecb1a71000a3f11be505e74e0081
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Deploy newly built site to S3 + CloudFront
        run: |
          aws s3 sync --delete public/ s3://${{ secrets.LTRR_SITE_BUCKET }}/
          aws cloudfront create-invalidation --distribution-id ${{ secrets.LTRR_SITE_CDN }} --paths '/*'      

